const QUIZZES = [
    {
        id: "genel-kultur",
        title: "Genel Kültür",
        icon: "\u{1F9E0}",
        desc: "Her alandan karışık bilgi soruları",
        color: "#6C5CE7",
        questions: [
            { q: "Dünya üzerinde en çok konuşulan dil hangisidir?", o: ["İngilizce", "Mandarin Çince", "İspanyolca", "Hintçe"], a: 1, e: "Mandarin Çince, yaklaşık 920 milyon ana dili konuşanıyla dünyanın en çok konuşulan dilidir." },
            { q: "Nobel Barış Ödülü hangi şehirde verilir?", o: ["Stockholm", "Oslo", "Kopenhag", "Helsinki"], a: 1, e: "Diğer Nobel ödülleri Stockholm'de verilirken, Barış Ödülü Oslo'da verilir. Bu Alfred Nobel'in vasiyetidir." },
            { q: "Işık hızı saniyede yaklaşık kaç kilometre yol alır?", o: ["150.000 km", "300.000 km", "450.000 km", "600.000 km"], a: 1, e: "Işık hızı saniyede tam olarak 299.792 km'dir. Güneş'ten Dünya'ya 8 dakika 20 saniyede ulaşır." },
            { q: "Türk bayrağı üzerinde hangi semboller bulunur?", o: ["Güneş ve ay", "Ay ve yıldız", "Yıldız ve güneş", "Hilal ve güneş"], a: 1, e: "Türk bayrağında kırmızı zemin üzerinde beyaz ay (hilal) ve yıldız bulunur." },
            { q: "Dünyanın en büyük okyanusu hangisidir?", o: ["Atlantik", "Hint", "Arktik", "Büyük (Pasifik)"], a: 3, e: "Pasifik Okyanusu 165.25 milyon km² ile dünyanın en büyük okyanusudur. Tüm kara parçalarından daha geniştir!" },
            { q: "Hangi vitamin güneş ışığıyla sentezlenir?", o: ["A vitamini", "B12 vitamini", "C vitamini", "D vitamini"], a: 3, e: "D vitamini, cilt güneş ışığına maruz kaldığında vücut tarafından sentezlenir. Kemik sağlığı için çok önemlidir." },
            { q: "Pi sayısının ilk üç basamağı nedir?", o: ["3.12", "3.14", "3.16", "3.18"], a: 1, e: "Pi sayısı 3.14159... şeklinde devam eder. Bir çemberin çevresinin çapına oranıdır." },
            { q: "İstanbul Boğazı hangi iki kıtayı birbirine bağlar?", o: ["Avrupa-Afrika", "Avrupa-Asya", "Asya-Afrika", "Avrupa-Amerika"], a: 1, e: "İstanbul Boğazı, Avrupa ve Asya kıtalarını ayıran 30 km uzunluğundaki doğal bir su yoludur." },
            { q: "Dünya üzerinde kaç tane okyanus vardır?", o: ["3", "4", "5", "6"], a: 2, e: "5 okyanus: Pasifik, Atlantik, Hint, Güney (Antarktika) ve Arktik (Kuzey Buz) Okyanusu." },
            { q: "Hangi gezegen 'Kızıl Gezegen' olarak bilinir?", o: ["Jüpiter", "Venüs", "Mars", "Merkür"], a: 2, e: "Mars, yüzeyindeki demir oksit (pas) nedeniyle kızıl renkte görünür." },
            { q: "DNA'nın açılımı nedir?", o: ["Deoksiribonükleik Asit", "Diribonükleik Asit", "Deoksiribonitik Asit", "Dinamik Nükleik Asit"], a: 0, e: "DNA, tüm canlıların genetik bilgisini taşıyan çift sarmal yapıda bir moleküldür." },
            { q: "Bir yılda kaç hafta vardır?", o: ["48", "50", "52", "54"], a: 2, e: "Bir yıl 365 gün, yani 52 hafta ve 1 gündür. Artık yıllarda 52 hafta ve 2 gün olur." },
            { q: "Dünyanın en uzun nehri hangisidir?", o: ["Amazon", "Nil", "Mississippi", "Yangtze"], a: 1, e: "Nil Nehri yaklaşık 6.650 km uzunluğuyla dünyanın en uzun nehridir. Afrika'nın kuzeydoğusundan Akdeniz'e akar." },
            { q: "Hangi element periyodik tabloda 'O' sembolüne sahiptir?", o: ["Altın", "Osmiyum", "Oksijen", "Oganeson"], a: 2, e: "Oksijen 'O' sembolüyle gösterilir. Altın 'Au', Osmiyum 'Os' sembolüne sahiptir." },
            { q: "İnsan vücudunda kaç kemik bulunur?", o: ["186", "206", "226", "246"], a: 1, e: "Yetişkin bir insanda 206 kemik bulunur. Bebekler yaklaşık 270 kemikle doğar, bazıları zamanla kaynaşır." },
            { q: "Mona Lisa tablosunu kim yapmıştır?", o: ["Michelangelo", "Raphael", "Leonardo da Vinci", "Donatello"], a: 2, e: "Mona Lisa, Leonardo da Vinci tarafından 1503-1519 yılları arasında yapılmıştır. Paris Louvre Müzesi'ndedir." },
            { q: "Dünyanın en küçük ülkesi hangisidir?", o: ["Monako", "Vatikan", "San Marino", "Liechtenstein"], a: 1, e: "Vatikan 0.44 km² ile dünyanın en küçük bağımsız devletidir. Roma şehrinin içinde yer alır." },
            { q: "Bir olimpiyat bayrağında kaç halka vardır?", o: ["4", "5", "6", "7"], a: 1, e: "5 halka 5 kıtayı temsil eder: mavi (Avrupa), sarı (Asya), siyah (Afrika), yeşil (Okyanusya), kırmızı (Amerika)." },
            { q: "Albert Einstein hangi ülkede doğmuştur?", o: ["İsviçre", "Avusturya", "Almanya", "Hollanda"], a: 2, e: "Einstein 1879'da Almanya'nın Ulm şehrinde doğmuştur. Sonradan İsviçre ve ABD vatandaşı olmuştur." },
            { q: "Dünyanın en yüksek binası hangi şehirdedir?", o: ["New York", "Dubai", "Shanghai", "Kuala Lumpur"], a: 1, e: "Burj Khalifa, 828 metre yüksekliğiyle Dubai'de bulunur ve dünyanın en yüksek binasıdır." }
        ]
    },
    {
        id: "bilim-teknoloji",
        title: "Bilim & Teknoloji",
        icon: "\u{1F52C}",
        desc: "Bilim ve teknoloji dünyasından sorular",
        color: "#00CEC9",
        questions: [
            { q: "İnterneti icat eden kişi kimdir?", o: ["Bill Gates", "Steve Jobs", "Tim Berners-Lee", "Mark Zuckerberg"], a: 2, e: "Tim Berners-Lee, 1989'da World Wide Web'i (WWW) icat etmiştir. İnternet altyapısı ise daha önce geliştirilmişti." },
            { q: "Hangi gaz atmosferin en büyük bölümünü oluşturur?", o: ["Oksijen", "Karbondioksit", "Azot", "Hidrojen"], a: 2, e: "Atmosferin %78'i azot, %21'i oksijen ve %1'i diğer gazlardan oluşur." },
            { q: "1 kilobayt (KB) kaç bayttır?", o: ["100", "512", "1000", "1024"], a: 3, e: "Bilgisayar biliminde 1 KB = 1024 bayttır (2'nin 10. kuvveti). SI standardında ise 1000 bayt olarak kabul edilir." },
            { q: "Elektrik ampulünü kim icat etmiştir?", o: ["Nikola Tesla", "Thomas Edison", "Alexander Bell", "Benjamin Franklin"], a: 1, e: "Thomas Edison 1879'da pratik kullanıma uygun elektrik ampulünü geliştirmiştir." },
            { q: "Hangi element periyodik tablonun ilk elementidir?", o: ["Helyum", "Lityum", "Hidrojen", "Karbon"], a: 2, e: "Hidrojen, atom numarası 1 olan en hafif ve evrendeki en bol bulunan elementtir." },
            { q: "Mars gezegenine gönderilen ilk başarılı rover hangisidir?", o: ["Spirit", "Opportunity", "Sojourner", "Curiosity"], a: 2, e: "Sojourner, 1997'de Mars Pathfinder misyonuyla Mars'a inen ilk başarılı gezici robottur." },
            { q: "Python programlama dili hangi yıl oluşturulmuştur?", o: ["1985", "1991", "1995", "2000"], a: 1, e: "Python, Guido van Rossum tarafından 1991'de oluşturulmuştur. Adı Monty Python komedi grubundan gelir." },
            { q: "Işık hangi parçacıklardan oluşur?", o: ["Nötrino", "Elektron", "Foton", "Proton"], a: 2, e: "Fotonlar, elektromanyetik radyasyonun kuantum parçacıklarıdır. Kütleleri yoktur ve ışık hızında hareket ederler." },
            { q: "İnsan genomunda yaklaşık kaç gen bulunur?", o: ["5.000", "10.000", "20.000", "50.000"], a: 2, e: "İnsan genomunda yaklaşık 20.000-25.000 gen bulunur. İlginçtir ki bu sayı bir domates bitkisinden azdır!" },
            { q: "Hangi şirket ilk iPhone'u piyasaya sürmüştür?", o: ["Samsung", "Apple", "Nokia", "Microsoft"], a: 1, e: "Apple, ilk iPhone'u 29 Haziran 2007'de Steve Jobs'ın sunumuyla piyasaya sürmüştür." },
            { q: "Su hangi sıcaklıkta kaynar (deniz seviyesinde)?", o: ["90°C", "95°C", "100°C", "110°C"], a: 2, e: "Su deniz seviyesinde 100°C'de kaynar. Yükseklik arttıkça kaynama noktası düşer." },
            { q: "Yerçekim kuvvetini açıklayan bilim insanı kimdir?", o: ["Galileo", "Einstein", "Newton", "Kepler"], a: 2, e: "Isaac Newton, 1687'de yerçekim yasasını formüle etmiştir. Efsaneye göre kafasına elma düşmesiyle ilham almıştır." },
            { q: "Hangi gezegen Güneş Sistemi'nde en büyüktür?", o: ["Satürn", "Jüpiter", "Uranüs", "Neptün"], a: 1, e: "Jüpiter, Dünya'nın 1.300 katı hacme sahip bir gaz devidir. 79'dan fazla uydusu vardır." },
            { q: "WiFi teknolojisi hangi ülkede geliştirilmiştir?", o: ["ABD", "Japonya", "Avustralya", "Güney Kore"], a: 2, e: "WiFi'nin temel teknolojisi Avustralyalı bilim insanı John O'Sullivan ve ekibi tarafından geliştirilmiştir." },
            { q: "Karbondioksitin kimyasal formülü nedir?", o: ["CO", "CO2", "C2O", "CO3"], a: 1, e: "CO2, bir karbon ve iki oksijen atomundan oluşur. Sera etkisinin ana bileşenlerinden biridir." },
            { q: "İlk programcı olarak kabul edilen kişi kimdir?", o: ["Alan Turing", "Ada Lovelace", "Charles Babbage", "Grace Hopper"], a: 1, e: "Ada Lovelace, 1843'te Charles Babbage'ın Analitik Motoru için ilk algoritmayı yazmıştır." },
            { q: "Bir atomun çekirdeğinde hangi parçacıklar bulunur?", o: ["Elektron ve nötron", "Proton ve nötron", "Foton ve elektron", "Nötrino ve proton"], a: 1, e: "Atom çekirdeğinde protonlar (+) ve nötronlar (nötr) bulunur. Elektronlar çekirdeğin etrafında döner." },
            { q: "Hangi teknoloji şirketi 'Don't be evil' sloganını kullanmıştır?", o: ["Apple", "Microsoft", "Google", "Amazon"], a: 2, e: "Google bu sloganı 2000'de benimsemiştir. 2018'de Alphabet'e geçişle 'Do the right thing' olarak değiştirilmiştir." },
            { q: "LED'in açılımı nedir?", o: ["Light Emitting Device", "Light Emitting Diode", "Laser Emitting Diode", "Light Energy Device"], a: 1, e: "LED (Işık Yayan Diyot), elektrik akımı geçtiğinde ışık üreten bir yarı iletken cihazdır." },
            { q: "Yapay zekâ (AI) terimi ilk kez hangi yıl kullanılmıştır?", o: ["1943", "1956", "1969", "1975"], a: 1, e: "John McCarthy, 1956'daki Dartmouth Konferansı'nda 'Artificial Intelligence' terimini ilk kez kullanmıştır." }
        ]
    },
    {
        id: "cografya",
        title: "Coğrafya",
        icon: "\u{1F30D}",
        desc: "Dünya coğrafyası hakkında her şey",
        color: "#00B894",
        questions: [
            { q: "Dünyanın en büyük çölünün adı nedir?", o: ["Gobi", "Sahra", "Kalahari", "Antarktika"], a: 3, e: "Antarktika, 14.2 milyon km² ile dünyanın en büyük çölüdür. Çöl tanımı sadece sıcak değil, kurak bölgeler için de geçerlidir." },
            { q: "Türkiye'nin en uzun nehri hangisidir?", o: ["Fırat", "Kızılırmak", "Sakarya", "Dicle"], a: 1, e: "Kızılırmak, 1.355 km ile Türkiye sınırları içindeki en uzun nehirdir." },
            { q: "Hangi ülke hem Avrupa'da hem Asya'da yer alır?", o: ["Mısır", "Rusya", "Türkiye", "Rusya ve Türkiye"], a: 3, e: "Hem Rusya hem Türkiye iki kıtada yer alır. Rusya Ural Dağları'yla, Türkiye İstanbul Boğazı'yla ikiye ayrılır." },
            { q: "Dünyanın en derin noktası neresidir?", o: ["Mariana Çukuru", "Tonga Çukuru", "Java Çukuru", "Porto Riko Çukuru"], a: 0, e: "Mariana Çukuru, Pasifik Okyanusu'nda 10.994 metre derinlikle dünyanın en derin noktasıdır." },
            { q: "Japonya'nın başkenti neresidir?", o: ["Osaka", "Kyoto", "Tokyo", "Nagoya"], a: 2, e: "Tokyo, 14 milyondan fazla nüfusuyla Japonya'nın başkenti ve en büyük şehridir." },
            { q: "Amazon yağmur ormanları en çok hangi ülkede yer alır?", o: ["Peru", "Kolombiya", "Brezilya", "Venezuela"], a: 2, e: "Amazon ormanlarının %60'ı Brezilya'dadır. Dünyanın oksijen üretiminin önemli bir kısmını sağlar." },
            { q: "Türkiye'de kaç coğrafi bölge vardır?", o: ["5", "6", "7", "8"], a: 2, e: "Türkiye'de 7 coğrafi bölge vardır: Marmara, Ege, Akdeniz, İç Anadolu, Karadeniz, Doğu Anadolu ve Güneydoğu Anadolu." },
            { q: "Dünyanın en büyük adası hangisidir?", o: ["Borneo", "Grönland", "Madagaskar", "Sumatra"], a: 1, e: "Grönland, 2.166.086 km² ile dünyanın en büyük adasıdır. Danimarka'ya bağlı özerk bir bölgedir." },
            { q: "Everest Dağı hangi ülkede bulunur?", o: ["Çin", "Hindistan", "Nepal", "Nepal-Çin sınırında"], a: 3, e: "Everest Dağı (8.849 m), Nepal ve Çin (Tibet) sınırında yer alır." },
            { q: "Nil Nehri hangi denize dökülmektedir?", o: ["Kızıldeniz", "Akdeniz", "Hint Okyanusu", "Karadeniz"], a: 1, e: "Nil Nehri, Mısır'ın kuzeyinde delta oluşturarak Akdeniz'e dökülür." },
            { q: "Hangi ülkenin bayrağında tek renk bulunur?", o: ["Japonya", "Libya (eski)", "Polonya", "Monako"], a: 1, e: "Libya'nın 1977-2011 arası bayrağı tamamen yeşildi ve dünyanın tek düz renkli bayrağıydı." },
            { q: "Avustralya'nın başkenti neresidir?", o: ["Sydney", "Melbourne", "Canberra", "Brisbane"], a: 2, e: "Canberra, Sydney ve Melbourne arasındaki rekabeti çözmek için 1913'te planlı olarak başkent yapılmıştır." },
            { q: "Türkiye'nin en büyük gölü hangisidir?", o: ["Tuz Gölü", "Van Gölü", "Beyşehir Gölü", "Burdur Gölü"], a: 1, e: "Van Gölü, 3.713 km² yüzölçümüyle Türkiye'nin en büyük gölüdür. Aynı zamanda dünyanın en büyük sodalı gölüdür." },
            { q: "Hangi ülke nüfus bakımından dünyanın en büyük ülkesidir?", o: ["Çin", "Hindistan", "ABD", "Endonezya"], a: 1, e: "Hindistan, 2023 itibarıyla Çin'i geçerek 1.4 milyardan fazla nüfusla dünyanın en kalabalık ülkesi olmuştur." },
            { q: "Brezilya'nın resmi dili nedir?", o: ["İspanyolca", "Portekizce", "Fransızca", "İngilizce"], a: 1, e: "Brezilya, Güney Amerika'da Portekizce konuşan tek ülkedir. Bu, Portekiz sömürge döneminden kaynaklanır." },
            { q: "Sahra Çölü hangi kıtada bulunur?", o: ["Asya", "Afrika", "Güney Amerika", "Avustralya"], a: 1, e: "Sahra Çölü, 9.2 milyon km² ile Afrika'nın kuzeyinde yer alan dünyanın en büyük sıcak çölüdür." },
            { q: "Kanada'nın en büyük şehri hangisidir?", o: ["Vancouver", "Montreal", "Toronto", "Ottawa"], a: 2, e: "Toronto, 6 milyondan fazla nüfusuyla Kanada'nın en büyük şehridir. Başkent ise Ottawa'dır." },
            { q: "Akdeniz Bölgesi'nin en önemli tarım ürünü hangisidir?", o: ["Buğday", "Zeytin", "Mısır", "Pamuk"], a: 1, e: "Akdeniz ikliminin sıcak ve kurak yazları zeytin yetiştirmeye çok uygundur. Türkiye dünya zeytin üretiminde ilk sıralardadır." },
            { q: "Dünyanın en küçük kıtası hangisidir?", o: ["Avrupa", "Antarktika", "Avustralya", "Güney Amerika"], a: 2, e: "Avustralya/Okyanusya, 8.5 milyon km² ile en küçük kıtadır." },
            { q: "Hangi şehir iki kıtada yer almaktadır?", o: ["Kahire", "Atina", "İstanbul", "Roma"], a: 2, e: "İstanbul, Boğaz'ın iki yakasında Avrupa ve Asya kıtalarına yayılan dünyadaki ender şehirlerden biridir." }
        ]
    },
    {
        id: "tarih",
        title: "Tarih",
        icon: "\u{1F3F0}",
        desc: "Dünya ve Türk tarihinden sorular",
        color: "#E17055",
        questions: [
            { q: "Türkiye Cumhuriyeti hangi yıl ilan edilmiştir?", o: ["1920", "1922", "1923", "1924"], a: 2, e: "29 Ekim 1923'te Mustafa Kemal Atatürk önderliğinde Türkiye Cumhuriyeti ilan edilmiştir." },
            { q: "İstanbul'un fethi hangi yıl gerçekleşmiştir?", o: ["1453", "1461", "1473", "1481"], a: 0, e: "29 Mayıs 1453'te Fatih Sultan Mehmet, Konstantinopolis'i fethederek Orta Çağ'ı sona erdirmiştir." },
            { q: "İkinci Dünya Savaşı hangi yıllar arasında yaşanmıştır?", o: ["1935-1943", "1937-1944", "1939-1945", "1941-1946"], a: 2, e: "1939'da Almanya'nın Polonya'yı işgaliyle başlamış, 1945'te Japonya'nın teslim olmasıyla sona ermiştir." },
            { q: "İlk insanlı Ay yolculuğu hangi yıl gerçekleşmiştir?", o: ["1965", "1967", "1969", "1971"], a: 2, e: "Apollo 11 ile Neil Armstrong ve Buzz Aldrin, 20 Temmuz 1969'da Ay'a ayak basan ilk insanlar olmuştur." },
            { q: "Mustafa Kemal Atatürk nerede doğmuştur?", o: ["İstanbul", "Ankara", "Selanik", "İzmir"], a: 2, e: "Atatürk, 1881'de bugünkü Yunanistan sınırları içinde kalan Selanik'te doğmuştur." },
            { q: "Fransız Devrimi hangi yıl başlamıştır?", o: ["1776", "1789", "1799", "1804"], a: 1, e: "14 Temmuz 1789'da Bastille Hapishanesi'nin basılmasıyla Fransız Devrimi başlamıştır." },
            { q: "Osmanlı Devleti hangi yıl kurulmuştur?", o: ["1243", "1299", "1326", "1354"], a: 1, e: "Osman Bey tarafından 1299'da kurulan Osmanlı Devleti, 623 yıl hüküm sürmüştür." },
            { q: "Berlin Duvarı hangi yıl yıkılmıştır?", o: ["1987", "1989", "1990", "1991"], a: 1, e: "9 Kasım 1989'da Berlin Duvarı yıkılmış, bu Soğuk Savaş'ın sembolik sonu olmuştur." },
            { q: "Çanakkale Savaşı hangi yıl yaşanmıştır?", o: ["1914", "1915", "1916", "1917"], a: 1, e: "1915'te yaşanan Çanakkale Savaşı'nda Osmanlı kuvvetleri İtilaf Devletleri'ni yenilgiye uğratmıştır." },
            { q: "Amerika kıtası hangi yıl keşfedilmiştir?", o: ["1488", "1492", "1497", "1502"], a: 1, e: "Kristof Kolomb, 12 Ekim 1492'de Bahama Adaları'na ulaşarak Amerika kıtasını Avrupalılara tanıtmıştır." },
            { q: "Mısır piramitlerini hangi medeniyet inşa etmiştir?", o: ["Romalılar", "Yunanlılar", "Eski Mısırlılar", "Fenikeliler"], a: 2, e: "Büyük Piramit yaklaşık MÖ 2560'ta inşa edilmiştir. Yaklaşık 2.3 milyon taş blok kullanılmıştır." },
            { q: "Birinci Dünya Savaşı'nı başlatan olay nedir?", o: ["Almanya'nın Polonya'yı işgali", "Avusturya veliahtının suikasti", "Lusitania'nın batması", "Rusya'nın seferberlik ilanı"], a: 1, e: "Avusturya-Macaristan veliahtı Arşidük Franz Ferdinand'ın Saraybosna'da suikaste uğraması savaşı tetiklemiştir." },
            { q: "İpek Yolu hangi ülkeden başlar?", o: ["Hindistan", "İran", "Çin", "Türkiye"], a: 2, e: "İpek Yolu, Çin'in Xi'an şehrinden başlayarak Akdeniz'e uzanan antik ticaret yoludur." },
            { q: "Atatürk'ün 'Yurtta sulh, cihanda sulh' sözü hangi konuyla ilgilidir?", o: ["Ekonomi", "Dış politika", "Eğitim", "Sağlık"], a: 1, e: "Bu söz Türkiye'nin barışçıl dış politika anlayışını özetler ve uluslararası ilişkilerde temel prensip olmuştur." },
            { q: "Sümerler hangi bölgede yaşamıştır?", o: ["Nil Vadisi", "Mezopotamya", "Anadolu", "Ege"], a: 1, e: "Sümerler, günümüz Irak'ında Fırat ve Dicle nehirleri arasındaki Mezopotamya'da yaşamışlardır. Yazıyı icat etmişlerdir." },
            { q: "TBMM ilk kez hangi tarihte açılmıştır?", o: ["23 Nisan 1920", "29 Ekim 1923", "30 Ağustos 1922", "19 Mayıs 1919"], a: 0, e: "23 Nisan 1920'de Ankara'da açılan TBMM, Kurtuluş Savaşı'nın yönetim merkezini oluşturmuştur." },
            { q: "Sanayi Devrimi ilk hangi ülkede başlamıştır?", o: ["Fransa", "Almanya", "İngiltere", "ABD"], a: 2, e: "Sanayi Devrimi 1760'larda İngiltere'de buhar makinesinin geliştirilmesiyle başlamıştır." },
            { q: "Fatih Sultan Mehmet İstanbul'u fethederken kaç yaşındaydı?", o: ["19", "21", "23", "25"], a: 1, e: "Fatih Sultan Mehmet, 1453'te İstanbul'u fethettiğinde henüz 21 yaşındaydı." },
            { q: "Roma İmparatorluğu'nun batı yarısı hangi yıl yıkılmıştır?", o: ["395", "410", "453", "476"], a: 3, e: "Batı Roma İmparatorluğu 476'da Germen komutan Odoaker tarafından yıkılmıştır." },
            { q: "Basmacılık hareketi hangi bölgede yaşanmıştır?", o: ["Kafkasya", "Balkanlar", "Orta Asya", "Ortadoğu"], a: 2, e: "Basmacılık, 1918-1934 arası Orta Asya'da Sovyet işgaline karşı yürütülen direniş hareketidir." }
        ]
    },
    {
        id: "spor",
        title: "Spor",
        icon: "\u26BD",
        desc: "Futboldan basketbola, spor dünyası",
        color: "#FDCB6E",
        questions: [
            { q: "FIFA Dünya Kupası'nı en çok kazanan ülke hangisidir?", o: ["Almanya", "Arjantin", "İtalya", "Brezilya"], a: 3, e: "Brezilya 5 kez (1958, 1962, 1970, 1994, 2002) Dünya Kupası kazanmıştır." },
            { q: "Bir futbol maçında kaç dakika oynanır?", o: ["80", "85", "90", "100"], a: 2, e: "Bir futbol maçı 2 yarı, toplam 90 dakikadır. Buna uzatma süreleri eklenir." },
            { q: "NBA'de bir basketbol sahası kaç feet uzunluğundadır?", o: ["84", "94", "100", "110"], a: 1, e: "NBA basketbol sahası 94 feet (28.7 metre) uzunluğunda ve 50 feet (15.2 metre) genişliğindedir." },
            { q: "Olimpiyat Oyunları kaç yılda bir yapılır?", o: ["2", "3", "4", "5"], a: 2, e: "Yaz ve Kış Olimpiyatları ayrı ayrı 4 yılda bir yapılır, ancak 2 yıl arayla düzenlenir." },
            { q: "Teniste 'Grand Slam' turnuvaları kaç tanedir?", o: ["3", "4", "5", "6"], a: 1, e: "4 Grand Slam: Avustralya Açık, Roland Garros (Fransa), Wimbledon (İngiltere) ve ABD Açık." },
            { q: "Türkiye Süper Lig'inde bir sezonda kaç takım yarışır?", o: ["16", "18", "19", "20"], a: 2, e: "Süper Lig'de 19 takım mücadele eder (2023-24 sezonundan itibaren 19 takıma çıkarılmıştır)." },
            { q: "Usain Bolt 100 metre dünya rekoru kaç saniyedir?", o: ["9.48", "9.58", "9.68", "9.78"], a: 1, e: "Usain Bolt, 2009 Berlin Dünya Şampiyonası'nda 9.58 saniye ile hâlâ kırılamayan rekor koymuştur." },
            { q: "Hangi ülke 2022 FIFA Dünya Kupası'na ev sahipliği yapmıştır?", o: ["Rusya", "Katar", "BAE", "Suudi Arabistan"], a: 1, e: "2022 Dünya Kupası, ilk kez bir Arap ülkesinde ve kışın (Kasım-Aralık) düzenlenmiştir." },
            { q: "Michael Jordan hangi NBA takımında ünlü olmuştur?", o: ["LA Lakers", "Boston Celtics", "Chicago Bulls", "Miami Heat"], a: 2, e: "Michael Jordan, Chicago Bulls ile 6 NBA şampiyonluğu kazanmıştır (1991-93, 1996-98)." },
            { q: "Bir voleybol takımında sahada kaç oyuncu bulunur?", o: ["5", "6", "7", "8"], a: 1, e: "Voleybolda her takımdan 6 oyuncu sahada yer alır. Liberolar savunma uzmanı olarak görev yapar." },
            { q: "Formula 1'de en çok şampiyonluk kazanan pilot kimdir?", o: ["Ayrton Senna", "Michael Schumacher", "Lewis Hamilton", "Sebastian Vettel"], a: 2, e: "Lewis Hamilton, 7 dünya şampiyonluğuyla Michael Schumacher'in rekorunu eşitlemiştir." },
            { q: "Galatasaray, Fenerbahçe ve Beşiktaş'ın ortak adı nedir?", o: ["İstanbul Üçlüsü", "Büyük Üçlü", "Üç Büyükler", "Süper Üçlü"], a: 2, e: "Türk futbolunun en köklü ve başarılı üç kulübü 'Üç Büyükler' olarak anılır." },
            { q: "Bir maraton kaç kilometredir?", o: ["36.195", "40.000", "42.195", "45.000"], a: 2, e: "42.195 km mesafe, 1908 Londra Olimpiyatları'nda kraliçenin sarayından stadyuma olan mesafeden gelir." },
            { q: "Cristiano Ronaldo hangi ülkelidir?", o: ["İspanya", "Brezilya", "Portekiz", "İtalya"], a: 2, e: "Ronaldo, Portekiz'in Madeira adasında doğmuştur. Portekiz milli takımının en golcü oyuncusudur." },
            { q: "Hangi spor dalında 'ace' terimi kullanılır?", o: ["Futbol", "Basketbol", "Tenis", "Yüzme"], a: 2, e: "Teniste 'ace', servis atışının rakip tarafından dokunulamadan sayı olmasıdır." },
            { q: "2024 Yaz Olimpiyatları hangi şehirde yapılmıştır?", o: ["Tokyo", "Los Angeles", "Paris", "Londra"], a: 2, e: "2024 Yaz Olimpiyatları, 100 yıl aradan sonra tekrar Paris'te düzenlenmiştir." },
            { q: "Bir buz hokeyi takımında sahada kaç oyuncu bulunur?", o: ["5", "6", "7", "8"], a: 1, e: "Buz hokeyinde kaleci dahil 6 oyuncu sahada bulunur: 1 kaleci, 2 defans, 3 forvet." },
            { q: "Lionel Messi 2022 Dünya Kupası'nda hangi ülke için oynadı?", o: ["İspanya", "Brezilya", "Arjantin", "Fransa"], a: 2, e: "Messi, Arjantin ile 2022 Dünya Kupası'nı kazanarak kariyerindeki en büyük eksikliği tamamlamıştır." },
            { q: "Wimbledon turnuvası hangi sporla ilgilidir?", o: ["Golf", "Kriket", "Tenis", "Polo"], a: 2, e: "Wimbledon, 1877'den beri düzenlenen dünyanın en eski ve en prestijli tenis turnuvasıdır." },
            { q: "Türkiye'nin olimpiyatlarda en başarılı olduğu spor dalı hangisidir?", o: ["Futbol", "Güreş", "Atletizm", "Halter"], a: 1, e: "Türkiye olimpiyat tarihinde en çok madalyayı güreş branşında kazanmıştır." }
        ]
    },
    {
        id: "sinema-dizi",
        title: "Sinema & Dizi",
        icon: "\u{1F3AC}",
        desc: "Film ve dizi dünyasından sorular",
        color: "#E84393",
        questions: [
            { q: "Oscar ödüllerini hangi kurum verir?", o: ["Hollywood Akademisi", "Amerikan Sinema Akademisi", "Film Enstitüsü", "Sundance Enstitüsü"], a: 1, e: "AMPAS (Academy of Motion Picture Arts and Sciences) 1929'dan beri Oscar ödüllerini verir." },
            { q: "Harry Potter serisini kim yazmıştır?", o: ["J.R.R. Tolkien", "J.K. Rowling", "C.S. Lewis", "George R.R. Martin"], a: 1, e: "J.K. Rowling, ilk kitabı 12 yayınevi tarafından reddedildikten sonra başarıya ulaşmıştır." },
            { q: "Titanic filminin yönetmeni kimdir?", o: ["Steven Spielberg", "James Cameron", "Martin Scorsese", "Ridley Scott"], a: 1, e: "James Cameron'ın yönettiği Titanic (1997), 11 Oscar kazanmıştır." },
            { q: "Game of Thrones dizisi kaç sezon sürdü?", o: ["6", "7", "8", "9"], a: 2, e: "Game of Thrones 2011-2019 arası 8 sezon yayınlanmıştır. George R.R. Martin'in romanlarına dayanır." },
            { q: "Marvel evrenindeki ilk film hangisidir?", o: ["Spider-Man", "Iron Man", "Hulk", "Captain America"], a: 1, e: "Iron Man (2008), MCU'nun (Marvel Sinematik Evreni) başlangıç filmidir." },
            { q: "Yüzüklerin Efendisi serisini kim yazmıştır?", o: ["C.S. Lewis", "J.K. Rowling", "J.R.R. Tolkien", "George R.R. Martin"], a: 2, e: "J.R.R. Tolkien bu eseri 1954-55'te yayımlamıştır. Modern fantastik edebiyatın babası kabul edilir." },
            { q: "Breaking Bad dizisinin ana karakteri kimdir?", o: ["Jesse Pinkman", "Walter White", "Hank Schrader", "Saul Goodman"], a: 1, e: "Walter White (Bryan Cranston), kimya öğretmeninden uyuşturucu baronu olan karakterdir." },
            { q: "Hangi film en çok Oscar ödülü kazanmıştır?", o: ["Titanic", "Ben-Hur", "Yüzüklerin Efendisi 3", "Her üç film eşit"], a: 3, e: "Üç film de 11'er Oscar kazanarak rekoru paylaşır: Ben-Hur (1959), Titanic (1997), LOTR: Kralın Dönüşü (2003)." },
            { q: "The Dark Knight filminde Joker'i kim canlandırmıştır?", o: ["Jack Nicholson", "Jared Leto", "Heath Ledger", "Joaquin Phoenix"], a: 2, e: "Heath Ledger bu rolüyle ölümünden sonra Oscar kazanmıştır. Performansı sinema tarihinin en iyilerinden sayılır." },
            { q: "Netflix hangi yıl kurulmuştur?", o: ["1995", "1997", "2000", "2003"], a: 1, e: "Netflix 1997'de DVD kiralama servisi olarak kurulmuş, 2007'de online yayına geçmiştir." },
            { q: "Stranger Things dizisi hangi on yılda geçmektedir?", o: ["1970'ler", "1980'ler", "1990'lar", "2000'ler"], a: 1, e: "Dizi 1983'te başlar ve 80'lerin popüler kültürüne bolca gönderme yapar." },
            { q: "Forrest Gump filminde baş rolü kim oynamıştır?", o: ["Brad Pitt", "Tom Hanks", "Robin Williams", "Jim Carrey"], a: 1, e: "Tom Hanks bu rolle 1995'te En İyi Erkek Oyuncu Oscar'ını kazanmıştır." },
            { q: "Inception filminin yönetmeni kimdir?", o: ["Quentin Tarantino", "David Fincher", "Christopher Nolan", "Denis Villeneuve"], a: 2, e: "Christopher Nolan'ın 2010 yapımı Inception, rüya içinde rüya konseptiyle büyük ses getirmiştir." },
            { q: "Friends dizisi kaç sezon boyunca yayınlanmıştır?", o: ["8", "9", "10", "12"], a: 2, e: "Friends 1994-2004 arası 10 sezon, toplam 236 bölüm yayınlanmıştır." },
            { q: "Star Wars evreninde 'Karanlık taraf'ın lideri kimdir?", o: ["Darth Vader", "Darth Maul", "İmparator Palpatine", "Kylo Ren"], a: 2, e: "İmparator Palpatine (Darth Sidious), Sith'lerin efendisi ve Galaktik İmparatorluğun kurucusudur." },
            { q: "Interstellar filminin konusu ne ile ilgilidir?", o: ["Savaş", "Uzay yolculuğu", "Zombiler", "Zaman yolculuğu"], a: 1, e: "Christopher Nolan'ın Interstellar (2014) filmi, insanlığı kurtarmak için solucan deliğinden geçen astronotları anlatır." },
            { q: "La Casa de Papel dizisi hangi ülke yapımıdır?", o: ["Meksika", "Brezilya", "İspanya", "Arjantin"], a: 2, e: "La Casa de Papel (Money Heist) İspanyol yapımıdır ve Netflix'in İngilizce olmayan en çok izlenen dizisi olmuştur." },
            { q: "Avatar (2009) filminin yönetmeni kimdir?", o: ["Steven Spielberg", "James Cameron", "Peter Jackson", "George Lucas"], a: 1, e: "James Cameron'ın Avatar'ı, 2.9 milyar dolarla tüm zamanların en yüksek hasılatlı filmidir." },
            { q: "The Shawshank Redemption filminin Türkçe adı nedir?", o: ["Esaretin Bedeli", "Umut Işığı", "Özgürlük Yolu", "Son Kaçış"], a: 0, e: "1994 yapımı Esaretin Bedeli, IMDb'de tüm zamanların en yüksek puanlı filmidir (9.3/10)." },
            { q: "Squid Game dizisi hangi ülke yapımıdır?", o: ["Japonya", "Çin", "Güney Kore", "Tayland"], a: 2, e: "Squid Game, 2021'de yayınlanarak Netflix tarihinin en çok izlenen dizisi olmuştur." }
        ]
    },
    {
        id: "matematik",
        title: "Matematik",
        icon: "\u{1F4D0}",
        desc: "Sayılar, formüller ve matematik bilgisi",
        color: "#0984E3",
        questions: [
            { q: "Bir üçgenin iç açılarının toplamı kaç derecedir?", o: ["90°", "180°", "270°", "360°"], a: 1, e: "Bir üçgenin iç açıları toplamı her zaman 180 derecedir. Bu temel geometri kuralıdır." },
            { q: "Fibonacci dizisinde 1, 1, 2, 3, 5'ten sonra hangi sayı gelir?", o: ["6", "7", "8", "10"], a: 2, e: "Fibonacci dizisinde her sayı önceki iki sayının toplamıdır: 3+5=8." },
            { q: "Sıfıra bölme işleminin sonucu nedir?", o: ["0", "1", "Sonsuz", "Tanımsız"], a: 3, e: "Matematikte bir sayının sıfıra bölünmesi tanımsızdır. Hiçbir sonuç üretmez." },
            { q: "Bir dairenin alanı nasıl hesaplanır?", o: ["2\u03C0r", "\u03C0r\u00B2", "2r\u00B2", "\u03C0d"], a: 1, e: "\u03C0r\u00B2 formülü ile dairenin alanı hesaplanır. 2\u03C0r ise çevre formülüdür." },
            { q: "25'in karekökü kaçtır?", o: ["3", "4", "5", "6"], a: 2, e: "5 x 5 = 25 olduğu için 25'in karekökü 5'tir." },
            { q: "Roma rakamlarında 'X' hangi sayıyı temsil eder?", o: ["5", "10", "50", "100"], a: 1, e: "Roma rakamlarında: I=1, V=5, X=10, L=50, C=100, D=500, M=1000." },
            { q: "Bir küpün kaç yüzeyi vardır?", o: ["4", "5", "6", "8"], a: 2, e: "Bir küpün 6 yüzeyi, 12 kenarı ve 8 köşesi vardır." },
            { q: "İki asal sayının toplamı her zaman hangi tür sayıdır?", o: ["Asal", "Çift", "Tek", "Hiçbiri kesin değil"], a: 3, e: "2+3=5 (tek), 3+5=8 (çift). 2 tek asal olduğu için sonuç her zaman aynı türde olmaz." },
            { q: "1'den 10'a kadar olan sayıların toplamı kaçtır?", o: ["45", "50", "55", "60"], a: 2, e: "1+2+3+...+10 = 55. Gauss formülü: n(n+1)/2 = 10x11/2 = 55." },
            { q: "Bir düzgün altıgenin kaç köşesi vardır?", o: ["4", "5", "6", "8"], a: 2, e: "Altıgen (hexagon) adından da anlaşılacağı gibi 6 köşeye sahiptir." },
            { q: "'Googol' sayısı kaçtır?", o: ["10\u2076", "10\u2079", "10\u00B9\u2070\u2070", "10\u00B9\u2070\u2070\u2070"], a: 2, e: "Googol, 10 üzeri 100'dür (1'in yanında 100 sıfır). Google şirketinin adı buradan esinlenilmiştir." },
            { q: "Paralel iki doğru kaç noktada kesişir?", o: ["0", "1", "2", "Sonsuz"], a: 0, e: "Paralel doğrular aynı düzlemde olup hiçbir noktada kesişmezler." },
            { q: "Bir sayı hem 2'ye hem 3'e bölünüyorsa, hangi sayıya da bölünür?", o: ["4", "5", "6", "8"], a: 2, e: "2 ve 3'ün en küçük ortak katı 6'dır. Dolayısıyla hem 2'ye hem 3'e bölünen her sayı 6'ya da bölünür." },
            { q: "En küçük asal sayı kaçtır?", o: ["0", "1", "2", "3"], a: 2, e: "2, en küçük ve tek çift asal sayıdır. 1 asal sayı olarak kabul edilmez." },
            { q: "Pisagor teoremine göre dik üçgende hipotenüs nasıl bulunur?", o: ["a+b", "a\u00B2+b\u00B2=c\u00B2", "axb", "a\u00B2-b\u00B2"], a: 1, e: "Pisagor teoremi: Dik üçgende hipotenüsün karesi, diğer iki kenarın karelerinin toplamına eşittir." },
            { q: "0! (sıfır faktöriyel) kaça eşittir?", o: ["0", "1", "Tanımsız", "-1"], a: 1, e: "Matematikte 0! = 1 olarak tanımlanır. Bu kombinatorik ve olasılık hesaplarında tutarlılık sağlar." },
            { q: "Bir yılda kaç saniye vardır (yaklaşık)?", o: ["31 milyon", "3.1 milyon", "310 bin", "3.1 milyar"], a: 0, e: "365 x 24 x 60 x 60 = 31.536.000, yani yaklaşık 31.5 milyon saniye." },
            { q: "Hangi sayı sistemi bilgisayarlarda kullanılır?", o: ["Onluk (desimal)", "İkilik (binary)", "Sekizlik (oktal)", "Altılık"], a: 1, e: "Bilgisayarlar ikilik (binary) sistemi kullanır: sadece 0 ve 1. Bu transistörlerin açık/kapalı durumunu temsil eder." },
            { q: "Bir çemberin iç açısı kaç derecedir?", o: ["180°", "270°", "360°", "720°"], a: 2, e: "Bir tam çember 360 derecedir. Bu Babillilerin 360 tabanlı sayı sisteminden gelir." },
            { q: "Altın oran yaklaşık olarak kaçtır?", o: ["1.414", "1.618", "2.718", "3.142"], a: 1, e: "Altın oran (phi) \u2248 1.618'dir. Doğada, sanatta ve mimaride sıkça karşımıza çıkar." }
        ]
    },
    {
        id: "muzik",
        title: "Müzik",
        icon: "\u{1F3B5}",
        desc: "Müzik dünyasından ilginç sorular",
        color: "#E17055",
        questions: [
            { q: "Ludwig van Beethoven hangi ülkelidir?", o: ["Avusturya", "Almanya", "İtalya", "Fransa"], a: 1, e: "Beethoven 1770'de Almanya'nın Bonn şehrinde doğmuştur. Hayatının büyük bölümünü Viyana'da geçirmiştir." },
            { q: "Bir oktavda kaç nota vardır?", o: ["5", "6", "7", "8"], a: 2, e: "Do, Re, Mi, Fa, Sol, La, Si - bir oktavda 7 ana nota vardır. 8. nota bir üst oktavın başlangıcıdır." },
            { q: "Dünyada en çok satan albüm hangisidir?", o: ["Abbey Road - Beatles", "Thriller - Michael Jackson", "Back in Black - AC/DC", "The Wall - Pink Floyd"], a: 1, e: "Michael Jackson'ın Thriller albümü 70 milyondan fazla kopya satarak tarihin en çok satan albümüdür." },
            { q: "'Bohemian Rhapsody' şarkısı hangi gruba aittir?", o: ["The Beatles", "Led Zeppelin", "Queen", "Pink Floyd"], a: 2, e: "Freddie Mercury'nin yazdığı bu şarkı 1975'te yayınlanmış ve rock tarihinin en ikonik parçalarından biri olmuştur." },
            { q: "Piyano kaç tuştan oluşur?", o: ["66", "76", "88", "92"], a: 2, e: "Standart bir piyano 88 tuştan oluşur: 52 beyaz ve 36 siyah tuş." },
            { q: "Türk müziğinde 'makam' ne demektir?", o: ["Ritim kalıbı", "Melodi yapısı", "Ses perdesi dizisi", "Çalgı türü"], a: 2, e: "Makam, belirli ses aralıklarıyla oluşturulan melodik yapıdır. Türk müziğinde 600'den fazla makam tanımlanmıştır." },
            { q: "Elvis Presley'e verilen lakap nedir?", o: ["Pop'un Kralı", "Rock'ın Kralı", "Müziğin Babası", "Blues'un Kralı"], a: 1, e: "Elvis Presley, 'Rock'ın Kralı' (King of Rock and Roll) olarak bilinir. 500 milyondan fazla albüm satmıştır." },
            { q: "Gitar normalde kaç telli bir çalgıdır?", o: ["4", "5", "6", "8"], a: 2, e: "Standart gitar 6 tellidir: Mi, La, Re, Sol, Si, Mi. Bas gitar ise genellikle 4 tellidir." },
            { q: "K-Pop müzik türü hangi ülkeye aittir?", o: ["Japonya", "Çin", "Güney Kore", "Tayland"], a: 2, e: "K-Pop (Korean Pop) Güney Kore kökenlidir. BTS ve BLACKPINK gibi gruplar dünya çapında popüler olmuştur." },
            { q: "Mozart ilk bestesini kaç yaşında yapmıştır?", o: ["3", "5", "7", "9"], a: 1, e: "Wolfgang Amadeus Mozart, 5 yaşında ilk bestesini yapmış, dahi çocuk olarak tarihe geçmiştir." },
            { q: "Hangi müzik aleti 'yaylı çalgılar' grubuna girer?", o: ["Flüt", "Keman", "Trompet", "Davul"], a: 1, e: "Keman, yaylı çalgılar ailesinin en tiz sesli üyesidir. Viyola, çello ve kontrbas da bu gruba girer." },
            { q: "Rap müzik hangi ülkede doğmuştur?", o: ["İngiltere", "Jamaika", "ABD", "Fransa"], a: 2, e: "Rap, 1970'lerde New York'un Bronx bölgesinde Afrika kökenli Amerikalı topluluklar arasında doğmuştur." },
            { q: "Do majör gamında kaç diyez veya bemol vardır?", o: ["0", "1", "2", "3"], a: 0, e: "Do majör gamı hiç diyez veya bemol içermez. Sadece beyaz tuşlardan (doğal notalar) oluşur." },
            { q: "Barış Manço'nun en ünlü şarkılarından biri hangisidir?", o: ["Yalnızlık", "Dönence", "Gülpembe", "Yaz Gazeteci Yaz"], a: 2, e: "Gülpembe (1981), Barış Manço'nun kızı için yazdığı ve Türk müzik tarihinin en sevilen şarkılarından biridir." },
            { q: "Spotify hangi ülkede kurulmuştur?", o: ["ABD", "İngiltere", "İsveç", "Almanya"], a: 2, e: "Spotify, 2006'da İsveç'in Stockholm şehrinde Daniel Ek ve Martin Lorentzon tarafından kurulmuştur." },
            { q: "En kalın sesli yaylı çalgı hangisidir?", o: ["Keman", "Viyola", "Çello", "Kontrbas"], a: 3, e: "Kontrbas, orkestradaki en büyük ve en kalın sesli yaylı çalgıdır. Yaklaşık 180 cm boyundadır." },
            { q: "Adele'in dünya çapında hit olan şarkısı hangisidir?", o: ["Shape of You", "Hello", "Havana", "Bad Guy"], a: 1, e: "Adele'in 'Hello' (2015) şarkısı ilk haftasında 1 milyondan fazla kopya satarak rekor kırmıştır." },
            { q: "Türkiye'nin Eurovision'da birinci olduğu yıl hangisidir?", o: ["2001", "2003", "2005", "Hiç olmadı"], a: 1, e: "Sertab Erener, 2003'te 'Everyway That I Can' şarkısıyla Türkiye'ye ilk ve tek Eurovision birinciliğini kazandırmıştır." },
            { q: "Hangi nota 'La' olarak adlandırılır ve akort referansıdır?", o: ["440 Hz", "220 Hz", "330 Hz", "550 Hz"], a: 0, e: "La notası 440 Hz frekansındadır ve enstrümanların akort edilmesinde evrensel referans olarak kullanılır." },
            { q: "The Beatles hangi şehirden çıkmıştır?", o: ["Londra", "Manchester", "Liverpool", "Birmingham"], a: 2, e: "The Beatles, 1960'da Liverpool'da kurulmuş ve müzik tarihinin en etkili grubu olmuştur." }
        ]
    },
    {
        id: "yemek-mutfak",
        title: "Yemek & Mutfak",
        icon: "\u{1F373}",
        desc: "Dünya mutfaklarından lezzetli sorular",
        color: "#E84393",
        questions: [
            { q: "Sushi hangi ülkenin geleneksel yemeğidir?", o: ["Çin", "Japonya", "Güney Kore", "Tayland"], a: 1, e: "Sushi, sirkeli pirinç ve çiğ balıktan yapılan Japonya'nın dünyaca ünlü yemeğidir." },
            { q: "Baklava hangi mutfağın en ünlü tatlılarından biridir?", o: ["İtalyan", "Fransız", "Türk", "Hint"], a: 2, e: "Baklava, ince yufka katları arasına fıstık veya ceviz konularak yapılan geleneksel Türk tatlısıdır." },
            { q: "Pizza'nın anavatanı hangi ülkedir?", o: ["ABD", "Yunanistan", "İtalya", "İspanya"], a: 2, e: "Pizza İtalya'nın Napoli şehrinde doğmuştur. Margherita pizza İtalyan kraliçesi onuruna yapılmıştır." },
            { q: "Wasabi genellikle hangi yemekle servis edilir?", o: ["Pasta", "Sushi", "Pizza", "Hamburger"], a: 1, e: "Wasabi, Japon mutfağında sushi ve sashimi ile servis edilen acı yeşil bir baharat sosu/macunudur." },
            { q: "Paella hangi ülkenin geleneksel yemeğidir?", o: ["Portekiz", "İtalya", "Meksika", "İspanya"], a: 3, e: "Paella, İspanya'nın Valencia bölgesinin pirinç bazlı geleneksel yemeğidir." },
            { q: "Kakaonun anavatanı neresidir?", o: ["Afrika", "Güney Amerika", "Güneydoğu Asya", "Avrupa"], a: 1, e: "Kakao ağacı Güney Amerika'nın Amazon bölgesinden gelmektedir. Aztekler ve Mayalar ilk kullananlar arasındadır." },
            { q: "Türk kahvesi UNESCO tarafından ne olarak kabul edilmiştir?", o: ["Süper gıda", "Somut kültürel miras", "Somut olmayan kültürel miras", "Dünya mirası"], a: 2, e: "Türk kahvesi kültürü ve geleneği, 2013'te UNESCO Somut Olmayan Kültürel Miras Listesi'ne alınmıştır." },
            { q: "Bir Michelin yıldızı ne anlama gelir?", o: ["Ucuz restoran", "Çok kaliteli restoran", "En büyük restoran", "En eski restoran"], a: 1, e: "Michelin yıldızları dünyanın en prestijli restoran derecelendirmesidir. 3 yıldız en yüksek puandır." },
            { q: "Kimchi hangi ülkenin fermente sebze yemeğidir?", o: ["Japonya", "Çin", "Güney Kore", "Vietnam"], a: 2, e: "Kimchi, baharatlı fermente lahana/turptan yapılan Kore'nin ulusal yemeğidir. Probiyotik açısından zengindir." },
            { q: "Safran baharatı hangi çiçekten elde edilir?", o: ["Gül", "Papatya", "Çiğdem", "Lavanta"], a: 2, e: "Safran, çiğdem (crocus) çiçeğinin kurutulmuş dişi organlarından elde edilir. Dünyanın en pahalı baharatıdır." },
            { q: "Guacamole'nin ana malzemesi nedir?", o: ["Domates", "Avokado", "Biber", "Soğan"], a: 1, e: "Guacamole, Meksika mutfağına ait avokado bazlı bir sostur. Aztekler tarafından icat edilmiştir." },
            { q: "Bir çay bardağı su yaklaşık kaç mililitredir?", o: ["100 ml", "150 ml", "200 ml", "250 ml"], a: 2, e: "Standart bir Türk çay bardağı yaklaşık 100-120 ml, su bardağı ise 200 ml civarındadır." },
            { q: "Croissant aslında hangi ülkede icat edilmiştir?", o: ["Fransa", "Avusturya", "İsviçre", "Belçika"], a: 1, e: "Croissant'ın atası olan 'kipferl' Avusturya'da ortaya çıkmıştır. Fransa'da bugünkü haline kavuşmuştur." },
            { q: "Lahmacun'un diğer adı nedir?", o: ["Türk pizzası", "Et ekmeği", "Açık pide", "Kıymalı ekmek"], a: 0, e: "Lahmacun, ince hamur üzerine kıymalı harç sürülerek pişirilen ve 'Türk pizzası' olarak da bilinen lezzettir." },
            { q: "Wasabi hangi renktedir?", o: ["Kırmızı", "Sarı", "Yeşil", "Kahverengi"], a: 2, e: "Gerçek wasabi açık yeşil renktedir. Restoranlarda genellikle boyalı yaban turpu ikame olarak kullanılır." },
            { q: "Tiramisù tatlısının ana malzemelerinden biri hangisidir?", o: ["Çikolata", "Mascarpone peyniri", "Krema", "Fıstık"], a: 1, e: "Tiramisù, mascarpone peyniri, espresso, kadayıf bisküvisi ve kakaodan yapılan İtalyan tatlısıdır." },
            { q: "Dünyada en çok tüketilen baharat hangisidir?", o: ["Tuz", "Karabiber", "Tarçın", "Kırmızıbiber"], a: 1, e: "Karabiber, dünyada en çok tüketilen ve 'baharatların kralı' olarak bilinen baharattır." },
            { q: "Iskender kebap hangi şehrin meşhur yemeğidir?", o: ["Adana", "Urfa", "Bursa", "Gaziantep"], a: 2, e: "İskender kebap, 1867'de Bursa'da İskender Efendi tarafından icat edilmiştir." },
            { q: "Tofu hangi bitkiden elde edilir?", o: ["Pirinç", "Soya fasulyesi", "Nohut", "Bezelye"], a: 1, e: "Tofu, soya sütünün pıhtılaştırılmasıyla elde edilen protein açısından zengin bir besindir. Çin'de 2000 yıl önce icat edilmiştir." },
            { q: "Bir yumurtanın ortalama pişme süresi (rafadan) kaç dakikadır?", o: ["3-4 dk", "6-7 dk", "10-12 dk", "15 dk"], a: 1, e: "Rafadan yumurta 6-7 dakikada pişer. 3-4 dakika kayısı kıvamı, 10+ dakika tam pişmiş olur." }
        ]
    },
    {
        id: "turkiye-ozel",
        title: "Türkiye Özel",
        icon: "\u{1F1F9}\u{1F1F7}",
        desc: "Türkiye hakkında bilmediğin şeyler",
        color: "#FF6348",
        questions: [
            { q: "Türkiye'nin yüzölçümü yaklaşık kaç km²'dir?", o: ["614.000", "714.000", "783.000", "850.000"], a: 2, e: "Türkiye'nin yüzölçümü 783.356 km²'dir. Avrupa ve Asya kıtalarına yayılır." },
            { q: "Kapadokya hangi ilde yer alır?", o: ["Kayseri", "Nevşehir", "Aksaray", "Hepsi"], a: 3, e: "Kapadokya bölgesi Nevşehir, Kayseri, Aksaray, Niğde ve Kırşehir illerini kapsar." },
            { q: "Türkiye'de kaç il vardır?", o: ["76", "79", "81", "83"], a: 2, e: "Türkiye'de 81 il bulunmaktadır. En son kurulan il 1999'da ayrılan Düzce'dir." },
            { q: "Efes Antik Kenti hangi ildedir?", o: ["Muğla", "İzmir", "Aydın", "Antalya"], a: 1, e: "Efes, İzmir'in Selçuk ilçesindedir. Artemis Tapınağı ile Dünyanın Yedi Harikası'ndan birine ev sahipliği yapmıştır." },
            { q: "Türkiye'nin en yüksek dağı hangisidir?", o: ["Uludağ", "Erciyes", "Süphan", "Ağrı Dağı"], a: 3, e: "Ağrı Dağı 5.137 metre ile Türkiye'nin en yüksek noktasıdır. Nuh'un Gemisi efsanesiyle ünlüdür." },
            { q: "Göbeklitepe kaç yıl öncesine tarihlenmektedir?", o: ["5.000", "8.000", "12.000", "15.000"], a: 2, e: "Göbeklitepe yaklaşık 12.000 yıllık olup bilinen en eski tapınak yapısıdır. Şanlıurfa'da bulunur." },
            { q: "Türkiye'nin en uzun sahil şeridine sahip ili hangisidir?", o: ["İzmir", "Antalya", "Muğla", "Mersin"], a: 2, e: "Muğla, yaklaşık 1.124 km ile Türkiye'nin en uzun sahil şeridine sahip ilidir." },
            { q: "Türk Lirası'nda (TL) hangi tarihî şahsiyetin portresi vardır?", o: ["Fatih Sultan Mehmet", "Mustafa Kemal Atatürk", "Kanuni Sultan Süleyman", "Mevlana"], a: 1, e: "Tüm Türk Lirası banknotlarının ön yüzünde Mustafa Kemal Atatürk'ün portresi bulunur." },
            { q: "Pamukkale travertenleri hangi ildedir?", o: ["Burdur", "Denizli", "Isparta", "Afyon"], a: 1, e: "Pamukkale, Denizli'dedir. Kalsiyum karbonat içeren sıcak su kaynaklarının oluşturduğu beyaz travertenlerle ünlüdür." },
            { q: "Türkiye'de çay en çok hangi bölgede yetiştirilir?", o: ["Ege", "Akdeniz", "Doğu Karadeniz", "Marmara"], a: 2, e: "Türkiye'nin çay üretiminin büyük bölümü Rize başta olmak üzere Doğu Karadeniz'de gerçekleşir." },
            { q: "Aspendos Antik Tiyatrosu hangi ildedir?", o: ["İzmir", "Antalya", "Mersin", "Hatay"], a: 1, e: "Aspendos, Antalya'nın Serik ilçesindedir. Dünyanın en iyi korunmuş Roma tiyatrolarından biridir." },
            { q: "Türkiye'nin nüfusu yaklaşık kaç milyondur?", o: ["65 milyon", "75 milyon", "85 milyon", "95 milyon"], a: 2, e: "Türkiye'nin nüfusu 2024 itibarıyla yaklaşık 85 milyondur." },
            { q: "Nemrut Dağı'ndaki dev heykeller hangi krallığa aittir?", o: ["Hitit", "Urartu", "Kommagene", "Lidya"], a: 2, e: "Nemrut Dağı'ndaki dev heykeller MÖ 1. yüzyılda Kommagene Kralı I. Antiokhos tarafından yaptırılmıştır." },
            { q: "Türkiye'nin ilk başkenti neresidir?", o: ["İstanbul", "Ankara", "Edirne", "Bursa"], a: 0, e: "Cumhuriyet ilan edilmeden önce TBMM'nin açıldığı 1920'den itibaren Ankara fiili başkent olmuştur. Osmanlı'nın ilk başkentleri Söğüt ve Bursa'dır." },
            { q: "Mevlana Müzesi hangi şehirdedir?", o: ["İstanbul", "Konya", "Bursa", "Kayseri"], a: 1, e: "Mevlana Celaleddin Rumi'nin türbesi Konya'dadır. Her yıl milyonlarca turist ziyaret eder." },
            { q: "Mardin'in mimari tarzı hangi taştan yapılmıştır?", o: ["Mermer", "Granit", "Kireç taşı", "Bazalt"], a: 2, e: "Mardin'in tarihi yapıları sarı-bej renkli kireç taşından inşa edilmiştir. Bu yüzden 'Sarı şehir' olarak bilinir." },
            { q: "Türkiye'nin en büyük havaalanı hangisidir?", o: ["Sabiha Gökçen", "İstanbul Havalimanı", "Esenboğa", "Adnan Menderes"], a: 1, e: "İstanbul Havalimanı, 2018'de açılmış olup dünyanın en büyük havalimanlarından biridir." },
            { q: "Sümela Manastırı hangi ildedir?", o: ["Artvin", "Trabzon", "Rize", "Giresun"], a: 1, e: "Sümela Manastırı, Trabzon'un Maçka ilçesinde sarp kayalıklara inşa edilmiş tarihi bir manastırdır." },
            { q: "Türkiye'nin en eski şehirlerinden biri olan Çatalhöyük hangi ildedir?", o: ["Konya", "Ankara", "Eskişehir", "Kütahya"], a: 0, e: "Çatalhöyük, Konya'da bulunan ve 9.000 yıllık geçmişe sahip dünyanın en eski yerleşim yerlerinden biridir." },
            { q: "Zeugma Mozaik Müzesi hangi şehirdedir?", o: ["İstanbul", "Ankara", "Gaziantep", "Hatay"], a: 2, e: "Zeugma Mozaik Müzesi Gaziantep'tedir ve dünyanın en büyük mozaik müzesidir. Ünlü 'Çingene Kızı' mozaiği burada sergilenir." }
        ]
    },
    {
        id: "felsefe",
        title: "Felsefe & Düşünce",
        icon: "\u{1F9D0}",
        desc: "Zor! Filozoflar ve düşünce akımları",
        color: "#636E72",
        questions: [
            { q: "'Düşünüyorum, öyleyse varım' sözü kime aittir?", o: ["Sokrates", "Aristoteles", "Descartes", "Kant"], a: 2, e: "René Descartes bu ünlü sözü (Cogito ergo sum) 1637'de 'Yöntem Üzerine Konuşma' eserinde yazmıştır." },
            { q: "Nihilizm ne demektir?", o: ["Her şeyin anlamsız olduğu görüşü", "Tanrı'nın varlığını reddetme", "Bilginin imkansızlığı", "Doğaya dönüş felsefesi"], a: 0, e: "Nihilizm, yaşamın nesnel bir anlamı, amacı veya değeri olmadığını savunan felsefi görüştür. Nietzsche ile özdeşleşmiştir." },
            { q: "Platon'un ünlü 'Mağara Alegorisi' neyi anlatır?", o: ["Tanrıların yaşamını", "Gerçeklik ve yanılsama ayrımını", "Devlet yönetimini", "Ölüm sonrası yaşamı"], a: 1, e: "Mağara Alegorisi, insanların gerçekliği değil gölgeleri gördüğünü anlatır. Bilgi ve cehalet arasındaki farkı simgeler." },
            { q: "Varoluşçuluk (Egzistansiyalizm) akımının öncüsü kimdir?", o: ["Hegel", "Marx", "Sartre", "Nietzsche"], a: 2, e: "Jean-Paul Sartre, 'Varoluş özden önce gelir' ilkesiyle varoluşçuluğun en önemli temsilcisidir." },
            { q: "Sokrates'in öğrencisi kimdir?", o: ["Aristoteles", "Platon", "Herakleitos", "Epikuros"], a: 1, e: "Platon, Sokrates'in öğrencisidir. Platon da Aristoteles'in hocasıdır. Üçü Antik Yunan felsefesinin temelini oluşturur." },
            { q: "Kategorik imperatif kavramını ortaya atan filozof kimdir?", o: ["Hegel", "Kant", "Hume", "Locke"], a: 1, e: "Immanuel Kant'ın ahlak felsefesinin temel kavramıdır: 'Eyleminin ilkesi evrensel yasa olabilecek şekilde davran.'" },
            { q: "Stoacılık felsefesinin temel ilkesi nedir?", o: ["Hazları yaşamak", "Duygulara hakim olmak", "Toplumdan uzaklaşmak", "Bilgiyi reddetmek"], a: 1, e: "Stoacılık, duyguları akılla kontrol etmeyi ve doğaya uygun yaşamayı savunur. Marcus Aurelius ünlü stoacılardan biridir." },
            { q: "'Toplum Sözleşmesi' kavramını geliştiren düşünür kimdir?", o: ["Voltaire", "Rousseau", "Montesquieu", "Diderot"], a: 1, e: "Jean-Jacques Rousseau'nun 'Toplum Sözleşmesi' (1762), modern demokrasi düşüncesinin temel eserlerinden biridir." },
            { q: "Epistemoloji ne ile ilgilenir?", o: ["Güzellik", "Bilgi", "Ahlak", "Varlık"], a: 1, e: "Epistemoloji (bilgi felsefesi), bilginin doğası, kaynağı ve sınırlarını inceler. 'Neyi bilebiliriz?' sorusunu sorar." },
            { q: "Karl Marx'ın en ünlü eseri hangisidir?", o: ["Leviathan", "Devlet", "Kapital", "Özgürlük Üzerine"], a: 2, e: "Das Kapital (1867), Marx'ın kapitalist sistemi eleştirdiği ve emek-değer teorisini açıkladığı başyapıtıdır." },
            { q: "Ütilitarizm (faydacılık) neyi savunur?", o: ["Bireyin özgürlüğünü", "En çok kişiye en çok mutluluk", "Devletin otoritesini", "Geleneklere bağlılığı"], a: 1, e: "Jeremy Bentham ve John Stuart Mill tarafından geliştirilen ütilitarizm, en fazla kişiye en fazla mutluluk getiren eylemi doğru kabul eder." },
            { q: "'Üstinsan' (Übermensch) kavramı kime aittir?", o: ["Hegel", "Schopenhauer", "Nietzsche", "Kierkegaard"], a: 2, e: "Friedrich Nietzsche, 'Böyle Buyurdu Zerdüşt' eserinde Üstinsan kavramını geliştirmiştir." },
            { q: "Empirizm neyi savunur?", o: ["Bilgi doğuştandır", "Bilgi deneyimden gelir", "Bilgi imkansızdır", "Bilgi toplumdan gelir"], a: 1, e: "Empirizm, tüm bilginin duyusal deneyimden kaynaklandığını savunur. John Locke ve David Hume önemli temsilcileridir." },
            { q: "Simone de Beauvoir hangi akımla özdeşleşmiştir?", o: ["Yapısalcılık", "Feminizm ve varoluşçuluk", "Pragmatizm", "Pozitivizm"], a: 1, e: "'İkinci Cins' (1949) eseri feminist felsefenin temel taşlarından biridir. 'Kadın doğulmaz, kadın olunur' sözü ona aittir." },
            { q: "Diyalektik yöntem hangi filozofla özdeşleşmiştir?", o: ["Kant", "Hegel", "Descartes", "Spinoza"], a: 1, e: "Hegel'in diyalektik yöntemi: tez, antitez ve sentez aşamalarıyla düşüncenin ilerlemesini açıklar." },
            { q: "'Panoptikon' kavramı hangi düşünürle ilişkilidir?", o: ["Foucault", "Derrida", "Deleuze", "Baudrillard"], a: 0, e: "Bentham'ın tasarladığı hapishane modelini Foucault, modern toplumda gözetim ve iktidar ilişkilerini açıklamak için kullanmıştır." },
            { q: "Pragmatizm felsefesi nerede doğmuştur?", o: ["Almanya", "Fransa", "İngiltere", "ABD"], a: 3, e: "Pragmatizm, 19. yüzyılda ABD'de Charles Peirce ve William James tarafından geliştirilmiştir." },
            { q: "Fenomenoloji akımının kurucusu kimdir?", o: ["Heidegger", "Husserl", "Sartre", "Merleau-Ponty"], a: 1, e: "Edmund Husserl, 20. yüzyılın başında fenomenolojiyi kurmuştur. Bilinç deneyimlerinin sistematik incelenmesini savunur." },
            { q: "Konfüçyüs hangi ülkenin düşünürüdür?", o: ["Japonya", "Hindistan", "Çin", "Kore"], a: 2, e: "Konfüçyüs (MÖ 551-479) Çinli filozof olup ahlak, aile ve toplum düzeni üzerine öğretileriyle bilinir." },
            { q: "'Oluş' kavramını felsefenin merkezine koyan Antik Yunan filozofu kimdir?", o: ["Parmenides", "Herakleitos", "Thales", "Anaksimandros"], a: 1, e: "Herakleitos 'Aynı nehirde iki kez yıkanamazsın' sözüyle sürekli değişimi (oluş) felsefenin merkezine koymuştur." }
        ]
    },
    {
        id: "uzay-astronomi",
        title: "Uzay & Astronomi",
        icon: "\u{1F680}",
        desc: "Zor! Evrenin sırları ve uzay bilimi",
        color: "#0652DD",
        questions: [
            { q: "Güneş Sistemi'ndeki en büyük uydu hangisidir?", o: ["Ay", "Titan", "Ganymede", "Europa"], a: 2, e: "Jüpiter'in uydusu Ganymede, 5.268 km çapıyla Güneş Sistemi'nin en büyük uydusudur. Merkür gezegeninden bile büyüktür." },
            { q: "Bir ışık yılı yaklaşık kaç trilyon kilometredir?", o: ["5.88", "9.46", "12.5", "15.3"], a: 1, e: "Bir ışık yılı yaklaşık 9.46 trilyon kilometredir. Bu, ışığın bir yılda katettiği mesafedir." },
            { q: "Kara delik nedir?", o: ["Karanlık bir gezegen", "Yerçekimi sonsuz olan uzay bölgesi", "Evrenin sınırı", "Işık saçmayan yıldız"], a: 1, e: "Kara delik, yerçekimi o kadar güçlü olan bir bölgedir ki ışık bile kaçamaz. Genellikle büyük yıldızların çökmesiyle oluşur." },
            { q: "Dünya'ya en yakın yıldız hangisidir?", o: ["Sirius", "Alpha Centauri", "Proxima Centauri", "Vega"], a: 2, e: "Proxima Centauri, 4.24 ışık yılı uzaklıkla Güneş'ten sonra Dünya'ya en yakın yıldızdır." },
            { q: "Güneş hangi tür bir yıldızdır?", o: ["Kırmızı dev", "Beyaz cüce", "Sarı cüce", "Süpernova"], a: 2, e: "Güneş, G2V sınıfı bir sarı cüce yıldızdır. Yaklaşık 4.6 milyar yaşındadır ve 5 milyar yıl daha parlayacaktır." },
            { q: "Hubble Uzay Teleskobu hangi yıl fırlatılmıştır?", o: ["1985", "1990", "1995", "2000"], a: 1, e: "Hubble, 1990'da fırlatılmış ve evrenin genişleme hızını ölçmemize yardımcı olmuştur." },
            { q: "Samanyolu galaksisinde yaklaşık kaç yıldız vardır?", o: ["1 milyon", "1 milyar", "100-400 milyar", "1 trilyon"], a: 2, e: "Samanyolu'nda tahminen 100 ila 400 milyar yıldız bulunur. Gözlemlenebilir evrende ise 200 milyar galaksi vardır." },
            { q: "Venüs gezegeninin bir günü, bir yılından uzun mudur?", o: ["Evet", "Hayır", "Eşittir", "Bilinmiyor"], a: 0, e: "Evet! Venüs'ün kendi etrafında dönmesi 243 Dünya günü, Güneş etrafında dönmesi ise 225 Dünya günü sürer." },
            { q: "Plüton neden gezegen statüsünü kaybetmiştir?", o: ["Çok küçük olduğu için", "Yörüngesini temizleyemediği için", "Uydusu olmadığı için", "Atmosferi olmadığı için"], a: 1, e: "2006'da IAU, gezegen tanımına 'yörüngesini temizleme' kriterini ekledi. Plüton bunu karşılayamadığı için 'cüce gezegen' oldu." },
            { q: "Kozmik mikrodalga arka plan radyasyonu neyin kanıtıdır?", o: ["Kara deliklerin", "Büyük Patlama'nın", "Paralel evrenlerin", "Uzaylıların"], a: 1, e: "1965'te keşfedilen CMB, Büyük Patlama'dan yaklaşık 380.000 yıl sonra yayılan radyasyonun kalıntısıdır." },
            { q: "Satürn'ün halkaları nedan oluşur?", o: ["Gaz ve toz", "Buz ve kaya parçacıkları", "Sıvı metal", "Plazma"], a: 1, e: "Satürn'ün halkaları büyük çoğunlukla buz parçacıkları ve kayadan oluşur. Halkaların genişliği 280.000 km'dir ama kalınlığı sadece 10 metre!" },
            { q: "James Webb Uzay Teleskobu hangi yıl fırlatılmıştır?", o: ["2019", "2020", "2021", "2022"], a: 2, e: "JWST, 25 Aralık 2021'de fırlatılmıştır. Kızılötesi gözlemlerle evrenin en erken dönemlerini inceleyebilir." },
            { q: "Nötron yıldızı nedir?", o: ["Soğumuş bir yıldız", "Çökmüş dev yıldızın çekirdeği", "Yeni doğan yıldız", "İkili yıldız sistemi"], a: 1, e: "Süpernova patlamasından sonra geriye kalan ultra yoğun çekirdektir. Bir çay kaşığı nötron yıldızı maddesinin ağırlığı 6 milyar tondur!" },
            { q: "Mars'ta bir gün yaklaşık kaç saat sürer?", o: ["20 saat", "24 saat 37 dk", "28 saat", "32 saat"], a: 1, e: "Mars'ta bir gün (sol) 24 saat 37 dakikadır, Dünya'ya çok yakındır. Ancak bir Mars yılı 687 Dünya günüdür." },
            { q: "Evrenin yaşı yaklaşık kaç milyar yıldır?", o: ["10.8", "13.8", "15.2", "18.5"], a: 1, e: "Evrenin yaşı yaklaşık 13.8 milyar yıldır. Bu, kozmik mikrodalga arka plan ölçümleriyle hesaplanmıştır." },
            { q: "Hangi gezegen 'yatan' eksende döner?", o: ["Venüs", "Uranüs", "Neptün", "Plüton"], a: 1, e: "Uranüs, eksen eğikliği 98° ile neredeyse 'yatarak' dönen tek gezegendir. Muhtemelen dev bir çarpışma sonucu bu hale gelmiştir." },
            { q: "Karanlık madde evrenin yüzde kaçını oluşturur?", o: ["%5", "%15", "%27", "%68"], a: 2, e: "Evrenin %27'si karanlık madde, %68'i karanlık enerji, sadece %5'i bildiğimiz normal maddedir." },
            { q: "Dünya'nın Ay'a olan uzaklığı yaklaşık kaç km'dir?", o: ["184.000", "284.000", "384.000", "484.000"], a: 2, e: "Dünya-Ay arası ortalama 384.400 km'dir. Işık bu mesafeyi yaklaşık 1.3 saniyede kat eder." },
            { q: "SpaceX'in yeniden kullanılabilir roketi hangisidir?", o: ["Saturn V", "Falcon 9", "Atlas V", "Ariane 5"], a: 1, e: "Falcon 9, SpaceX'in yeniden kullanılabilir ilk kademeli roketidir. Bu sayede uzay uçuşları çok daha ucuzlamıştır." },
            { q: "Gözlemlenebilir evrenin çapı yaklaşık kaç milyar ışık yılıdır?", o: ["13.8", "46", "93", "200"], a: 2, e: "Gözlemlenebilir evrenin çapı yaklaşık 93 milyar ışık yılıdır. Evrenin genişlemesi nedeniyle yaşından daha büyüktür." }
        ]
    },
    {
        id: "mitoloji",
        title: "Mitoloji",
        icon: "\u{1F531}",
        desc: "Zor! Yunan, Türk ve dünya mitolojisi",
        color: "#6F1E51",
        questions: [
            { q: "Yunan mitolojisinde tanrıların kralı kimdir?", o: ["Poseidon", "Hades", "Zeus", "Ares"], a: 2, e: "Zeus, Olympos Dağı'nda yaşayan tanrıların kralıdır. Şimşek ve gök gürültüsü onun simgesidir." },
            { q: "Truva Savaşı'nın başlamasına neden olan olay nedir?", o: ["Altın elma anlaşmazlığı", "Zeus'un öfkesi", "Deniz tanrısının laneti", "Bir kehanet"], a: 0, e: "Paris'in Aphrodite'ye altın elmayı vermesi ve ödül olarak Helena'yı kaçırması Truva Savaşı'nı başlatmıştır." },
            { q: "Medusa'nın saçları neden yılandan oluşuyordu?", o: ["Doğuştan", "Zeus'un cezası", "Athena'nın laneti", "Kendi isteği"], a: 2, e: "Güzel Medusa, Athena'nın tapınağında Poseidon ile birlikte olunca Athena onu cezalandırarak saçlarını yılana çevirmiştir." },
            { q: "İskandinav mitolojisinde dünyanın sonu neyle anlatılır?", o: ["Ragnarök", "Valhalla", "Bifrost", "Yggdrasil"], a: 0, e: "Ragnarök, tanrıların ve dünyanın sonunu anlatan büyük savaştır. Odin, Thor ve Loki bu savaşta ölür." },
            { q: "Mısır mitolojisinde ölüler diyarının tanrısı kimdir?", o: ["Ra", "Horus", "Anubis", "Osiris"], a: 3, e: "Osiris, ölüler diyarının ve yeniden doğuşun tanrısıdır. Kardeşi Set tarafından öldürülmüş ama eşi Isis tarafından diriltilmiştir." },
            { q: "Prometheus insanlara ne verdiği için cezalandırılmıştır?", o: ["Bilgi", "Ateş", "Silah", "İmmortalite"], a: 1, e: "Prometheus, Olympos'tan ateşi çalıp insanlara vermiştir. Zeus onu kayaya zincirleyerek her gün ciğerinin kartal tarafından yenmesine hükmetmiştir." },
            { q: "Türk mitolojisinde gökyüzü tanrısı kimdir?", o: ["Erlik", "Tengri", "Umay", "Kayra Han"], a: 1, e: "Tengri (Gök Tanrı), eski Türk inancında evrenin yaratıcısı ve en yüce varlıktır. Tengricilik bu inançtan doğmuştur." },
            { q: "Minotaur hangi yapıda hapsedilmiştir?", o: ["Olympos", "Labirent", "Partenon", "Akropolis"], a: 1, e: "Yarı insan yarı boğa Minotaur, Girit'te Daedalus'un inşa ettiği Labirent'te hapsedilmiştir. Theseus tarafından öldürülmüştür." },
            { q: "Hint mitolojisinde evrenin koruyucusu kimdir?", o: ["Brahma", "Vishnu", "Shiva", "Ganesha"], a: 1, e: "Hindu üçlemesinde Brahma yaratıcı, Vishnu koruyucu, Shiva ise yıkıcıdır." },
            { q: "Achilles'in tek zayıf noktası neresidir?", o: ["Kalbi", "Gözleri", "Topuğu", "Bileği"], a: 2, e: "Annesi Thetis onu Styx Nehri'ne batırırken topuğundan tutmuştu. Bu yüzden topuğu ölümsüzlükten nasibini almamıştır." },
            { q: "Japon mitolojisinde güneş tanrıçası kimdir?", o: ["Izanami", "Amaterasu", "Tsukuyomi", "Susanoo"], a: 1, e: "Amaterasu, Şinto dininde en yüce tanrıça ve Japon imparator ailesinin mitolojik atasıdır." },
            { q: "Pandora'nın kutusunda en son ne kalmıştır?", o: ["Aşk", "Nefret", "Umut", "Ölüm"], a: 2, e: "Pandora kutuyu açınca tüm kötülükler dünyaya yayılmış, ama kutunun dibinde umut kalmıştır." },
            { q: "Odin hangi mitolojinin baş tanrısıdır?", o: ["Kelt", "İskandinav", "Slav", "Yunan"], a: 1, e: "Odin, İskandinav (Norse) mitolojisinin bilgelik, savaş ve ölüm tanrısıdır. Bir gözünü bilgelik kuyusuna vermiştir." },
            { q: "Türk mitolojisinde yeraltı dünyasının tanrısı kimdir?", o: ["Tengri", "Umay", "Erlik", "Kayra Han"], a: 2, e: "Erlik Han, Türk mitolojisinde yeraltı dünyasının ve kötülüğün tanrısıdır. Şamanizm'de önemli bir figürdür." },
            { q: "Sisifos hangi cezaya çarptırılmıştır?", o: ["Sonsuz açlık", "Kaya yuvarlamak", "Zincirlenmek", "Yanmak"], a: 1, e: "Sisifos, tanrıları aldattığı için sonsuza dek bir kayayı tepeye çıkarmak ve tekrar düşmesini izlemekle cezalandırılmıştır." },
            { q: "Feniks (Anka kuşu) neyi simgeler?", o: ["Gücü", "Bilgeliği", "Yeniden doğuşu", "Ölümü"], a: 2, e: "Feniks, kendi külllerinden yeniden doğan efsanevi kuştur. Ölümsüzlük ve yenilenmenin evrensel sembolüdür." },
            { q: "Loki hangi mitolojinin hileci tanrısıdır?", o: ["Yunan", "Mısır", "İskandinav", "Kelt"], a: 2, e: "Loki, İskandinav mitolojisinin şekil değiştiren hileci tanrısıdır. Ragnarök'te tanrılara karşı savaşır." },
            { q: "Poseidon neyin tanrısıdır?", o: ["Gökyüzü", "Yeraltı", "Deniz", "Savaş"], a: 2, e: "Poseidon, denizlerin, depremlerin ve atların tanrısıdır. Zeus'un kardeşidir. Üç dişli çatalı (trident) simgesidir." },
            { q: "Azteklerin güneş tanrısı kimdir?", o: ["Quetzalcoatl", "Huitzilopochtli", "Tezcatlipoca", "Tlaloc"], a: 1, e: "Huitzilopochtli, Aztek mitolojisinin güneş ve savaş tanrısıdır. Aztek başkenti Tenochtitlan onun onuruna kurulmuştur." },
            { q: "Narkissos hangi çiçeğe dönüşmüştür?", o: ["Gül", "Lale", "Nergis", "Sümbül"], a: 2, e: "Narkissos, sudaki yansımasına aşık olup eriyerek nergis (narcissus) çiçeğine dönüşmüştür. Narsisizm terimi buradan gelir." }
        ]
    },
    {
        id: "tip-vucud",
        title: "Tıp & İnsan Vücudu",
        icon: "\u{1FA7A}",
        desc: "Zor! İnsan vücudu ve tıp bilgisi",
        color: "#C0392B",
        questions: [
            { q: "İnsan vücudundaki en büyük organ hangisidir?", o: ["Karaciğer", "Beyin", "Deri", "Akciğer"], a: 2, e: "Deri, yaklaşık 2 m² yüzey alanıyla vücudun en büyük organıdır. Yetişkin bir insanda 3.6-4.5 kg ağırlığındadır." },
            { q: "Kalp günde yaklaşık kaç kez atar?", o: ["50.000", "100.000", "150.000", "200.000"], a: 1, e: "Kalp günde yaklaşık 100.000 kez atar ve yaklaşık 7.500 litre kan pompalar." },
            { q: "Hangi kan grubu 'evrensel verici' olarak bilinir?", o: ["A Rh+", "B Rh-", "AB Rh+", "0 Rh-"], a: 3, e: "0 Rh- kan grubu, antijen içermediği için tüm kan gruplarına verilebilir." },
            { q: "İnsan beyninde yaklaşık kaç nöron bulunur?", o: ["1 milyon", "100 milyon", "86 milyar", "1 trilyon"], a: 2, e: "İnsan beyninde yaklaşık 86 milyar nöron ve bunlar arasında trilyonlarca sinaptik bağlantı vardır." },
            { q: "Vücuttaki en küçük kemik hangisidir?", o: ["El bilek kemiği", "Üzengi kemiği", "Kuyruk sokumu", "Ayak parmak kemiği"], a: 1, e: "Üzengi kemiği (stapes), orta kulakta bulunan ve sadece 2.5 mm uzunluğundaki en küçük kemiktir." },
            { q: "Penisilini kim keşfetmiştir?", o: ["Louis Pasteur", "Alexander Fleming", "Robert Koch", "Joseph Lister"], a: 1, e: "Alexander Fleming, 1928'de tesadüfen penisilini keşfetmiştir. Bu keşif modern antibiyotik çağını başlatmıştır." },
            { q: "Vücuttaki en uzun kemik hangisidir?", o: ["Tibia", "Humerus", "Femur", "Radius"], a: 2, e: "Femur (uyluk kemiği), vücudun en uzun ve en güçlü kemiğidir. Boy uzunluğunun yaklaşık %26'sı kadardır." },
            { q: "İnsan DNA'sı yaklaşık kaç baz çiftinden oluşur?", o: ["3 milyon", "30 milyon", "3 milyar", "30 milyar"], a: 2, e: "İnsan DNA'sı yaklaşık 3 milyar baz çiftinden oluşur. Tüm hücrelerdeki DNA açılsa Güneş'e gidip gelecek mesafededir." },
            { q: "Hangi vitamin eksikliği skorbüt hastalığına yol açar?", o: ["A vitamini", "B vitamini", "C vitamini", "D vitamini"], a: 2, e: "C vitamini (askorbik asit) eksikliği skorbüte neden olur. Tarihte denizcilerde çok yaygındı." },
            { q: "Vücutta en hızlı yenilenen hücreler hangileridir?", o: ["Beyin hücreleri", "Kas hücreleri", "Bağırsak epitel hücreleri", "Kemik hücreleri"], a: 2, e: "İnce bağırsak epitel hücreleri her 3-5 günde bir tamamen yenilenir." },
            { q: "İnsülin hangi organda üretilir?", o: ["Karaciğer", "Böbrek", "Pankreas", "Tiroit"], a: 2, e: "İnsülin, pankreastaki Langerhans adacıklarındaki beta hücrelerinde üretilir. Kan şekerini düzenler." },
            { q: "İnsan gözü kaç megapiksel çözünürlüğe eşdeğerdir?", o: ["12 MP", "50 MP", "576 MP", "1000 MP"], a: 2, e: "İnsan gözü yaklaşık 576 megapiksel çözünürlüğe sahiptir. Ancak beyin görüntüyü işlerken çok daha karmaşık süreçler devreye girer." },
            { q: "Vücuttaki en güçlü kas hangisidir?", o: ["Biceps", "Çene kası (masseter)", "Quadriceps", "Kalp kası"], a: 1, e: "Vücuttaki birim alan başına en güçlü kas çene kası (masseter) dır. 80 kg'a kadar ısırma kuvveti üretebilir." },
            { q: "Yetişkin bir insanın vücudunda yaklaşık kaç litre kan vardır?", o: ["3 litre", "5 litre", "7 litre", "10 litre"], a: 1, e: "Yetişkin bir insanda vücut ağırlığının yaklaşık %7'si kadar kan bulunur, ortalama 5 litre civarıdır." },
            { q: "Antibiyotikler hangi tür enfeksiyonlara karşı etkilidir?", o: ["Viral", "Bakteriyel", "Fungal", "Parazitik"], a: 1, e: "Antibiyotikler sadece bakteriyel enfeksiyonlara karşı etkilidir. Grip gibi viral hastalıklarda işe yaramaz." },
            { q: "İnsan vücudundaki en büyük iç organ hangisidir?", o: ["Mide", "Akciğer", "Karaciğer", "Dalak"], a: 2, e: "Karaciğer yaklaşık 1.5 kg ile vücudun en büyük iç organıdır. 500'den fazla fonksiyonu vardır." },
            { q: "Bir kırmızı kan hücresinin ömrü yaklaşık kaç gündür?", o: ["30", "60", "120", "180"], a: 2, e: "Kırmızı kan hücreleri (eritrositler) yaklaşık 120 gün yaşar. Vücut her saniye 2 milyon yeni eritrosit üretir." },
            { q: "Aşı hangi prensiple çalışır?", o: ["Hastalığı tedavi eder", "Bağışıklık sistemini önceden hazırlar", "Virüsleri öldürür", "Kan hücrelerini güçlendirir"], a: 1, e: "Aşılar, zayıflatılmış veya ölü patojenlerle bağışıklık sistemini eğiterek gelecekteki enfeksiyonlara karşı hazırlar." },
            { q: "İnsan iskeletinin yüzde kaçı su içerir?", o: ["%10", "%22", "%31", "%45"], a: 2, e: "Kemikler yaklaşık %31 oranında su içerir. Yetişkin kemik dokusu canlı ve sürekli yenilenen bir dokudur." },
            { q: "Hangi beyin yarımküresi konuşma yeteneğini kontrol eder (çoğu insanda)?", o: ["Sağ", "Sol", "Her ikisi eşit", "Beyincik"], a: 1, e: "İnsanların %95'inde konuşma merkezi (Broca ve Wernicke alanları) sol beyin yarımküresindedir." }
        ]
    }
];
